const $=e=>document.querySelector(e),t=e=>{const t=$('#toast');t&&(t.textContent=e,t.classList.add('show'),setTimeout(()=>t.classList.remove('show'),2400))},a=()=>{try{return JSON.parse(localStorage.getItem('profile')||'{}')}catch(e){return{}}},o=e=>localStorage.setItem('profile',JSON.stringify(e)),n=()=>{const e={age:$('#age')?.value||null,height:$('#height')?.value||null,hair:$('#hair')?.value||null,body:$('#body')?.value||null,religion:$('#religion')?.value||'',diet:$('#diet')?.value||'',tags:$('#tags')?.value||'',pref:$('#pref')&&Array.from($('#pref').selectedOptions).map(e=>e.value)||[],range:$('#range')?.value||null,pref_same_religion:$('#pref_same_religion')?.checked||!1,pref_same_diet:$('#pref_same_diet')?.checked||!1};o(e),t('Profil enregistré localement.'),c()},s=()=>{localStorage.clear(),t('Données locales effacées.'),setTimeout(()=>location.reload(),700)};let l=!1,r=0;const d=e=>{l=e,t(e?'Vous êtes disponible pendant 60 min (démo).':'Indisponible.')},i=()=>{if(!l){t('Activez “Disponible” d’abord.');return}const e=a(),o=$('#filter_same_religion')?.checked,n=$('#filter_same_diet')?.checked;if(o&&!e.religion||n&&!e.diet){t('Personne compatible sous ces filtres (démo).');return}r+=1;const s=$('#prox-count .v');s&&(s.textContent=String(r)),t('Quelqu’un de compatible est tout près (~100 m).')},p=()=>{d(!1),t('Mode discret activé pour 3 heures (démo).')},m=()=>{if(!l){t('Activez “Disponible” d’abord.');return}const e=$('#meet-card');e.innerHTML=`
    <h2>Point de rencontre</h2>
    <p>Choisissez un lieu public à mi-chemin :</p>
    <ul>
      <li>Entrée principale du Parc Central</li>
      <li>Devant le Café Horizon (terrasse)</li>
      <li>Fontaine du Square Victor</li>
    </ul>
    <p><b>Décrivez votre tenue pour vous reconnaître</b> (ex. “manteau rouge”, “robe noire”, “veste bleue”).</p>
    <div class="row">
      <input id="desc-tenue" placeholder="Ex. manteau rouge">
      <button class="btn" id="btn-share-desc">Partager ma description</button>
    </div>
    <div id="desc-status" class="notice" style="margin-top:8px"></div>
    <p class="notice">Pas de chat dans l’app. Allez vous dire bonjour directement.</p>
  `,$('#btn-share-desc')?.addEventListener('click',u),t('Rencontre prête. Ajoutez votre description.')},u=()=>{const e=$('#desc-tenue')?.value.trim();e?( $('#desc-status').innerHTML=`Description partagée : <b>${e}</b>. En attente de l’autre personne… (démo)`,t('Description envoyée (démo).')):t('Ajoutez une courte description (ex. “manteau rouge”).')},h=()=>{const e='sms:?&body='+encodeURIComponent('Besoin d’un check-in. Je suis à un rendez-vous. Tout va bien ?');location.href=e},c=()=>{const e=$('#profile-summary');if(!e)return;const t=a(),o=[];t.age&&o.push(`<chip>Âge ${t.age}</chip>`),t.height&&o.push(`<chip>${t.height} cm</chip>`),t.hair&&o.push(`<chip>Cheveux ${t.hair}</chip>`),t.body&&o.push(`<chip>Corps ${t.body}</chip>`),t.religion&&o.push(`<chip>Religion ${t.religion}</chip>`),t.diet&&o.push(`<chip>Régime ${t.diet}</chip>`),t.tags&&o.push(`<chip>Tags: ${t.tags}</chip>`),e.innerHTML=o.length?o.join(' '):'<small>Aucun profil sauvegardé pour l’instant.</small>'};document.addEventListener('DOMContentLoaded',()=>{$('#btn-save-profile')?.addEventListener('click',n),$('#btn-clear')?.addEventListener('click',s),$('#btn-available')?.addEventListener('click',()=>{d(!l)}),$('#btn-stealth')?.addEventListener('click',p),$('#btn-simulate')?.addEventListener('click',i),$('#btn-accept')?.addEventListener('click',m),$('#btn-decline')?.addEventListener('click',()=>{$('#meet-card').innerHTML='<p class="notice">Invitation refusée. À une prochaine fois.</p>'}),$('#btn-panic')?.addEventListener('click',h),c()});